### PR TITLE
Bump VS installation version to 2019

### PR DESCRIPTION
**Pull request by krOoze**
seems to work so far

### CODE REVIEW

**Comment by krOoze** [comment]
@michaldudak Hey, do you plan to update this extension to VS2019?

**Comment by michaldudak** [comment]
Hi, sorry, I somehow missed the pull request notification. I'll take a look at it later today.

**Review by michaldudak — APPROVED** [review]

**Comment by michaldudak** [comment]
The package is being processed by the VS Marketplace and should be available soon. Sorry it took so long.

**Comment by krOoze** [comment]
@michaldudak Ups, it actually does not work for new 16.1.* versions. Fix in pr #4 .

**Pull request merged**
